# Generated by Django 4.2.11 on 2024-11-22 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='card',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='La cédula debe contener exactamente 10 números', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 10 números', regex='^\\d{10}$')]),
        ),
    ]
