# Generated by Django 4.2.11 on 2024-11-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_value_alter_client_card_alter_client_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='value',
            new_name='valor',
        ),
    ]
