# Generated by Django 4.2.11 on 2024-11-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_client_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
