# Generated by Django 4.2.11 on 2024-11-23 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='valor',
        ),
    ]
