# Generated by Django 4.2.11 on 2024-11-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='phone',
        ),
        migrations.AddField(
            model_name='provider',
            name='product',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='valor',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
